export {default as Dashboard} from './Dashboard'
export {default as Header} from './Header/index.vue'
export {default as Footer} from './Footer'
export {default as Sidebar} from './Sidebar/index.vue'
export {default as PageHeader} from './PageHeader/index.vue'
export {default as BreadCrumbs} from './BreadCrumbs/index.vue'
